// import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "./context/Providers";
import NavBar from "./components/NavBar";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body className={``}>
      <Provider>
          <main className=" mx-auto  min-h-screen ">
            <header className="flex justify-around">
              {/* <NavBarMain /> */}
              <NavBar/>
            </header>
            <main>{children}</main>
            <footer></footer>
          </main>
      </Provider>
        </body>
    </html>
  );
}
